(()=>{"use strict";
const menu=document.querySelector(".menu-toggle"),nav=document.querySelector(".site-nav");
if(menu&&nav){const close=()=>{nav.classList.remove("is-open");menu.setAttribute("aria-expanded","false");menu.setAttribute("aria-label","Open navigation")};menu.addEventListener("click",()=>{const open=nav.classList.toggle("is-open");menu.setAttribute("aria-expanded",String(open));menu.setAttribute("aria-label",open?"Close navigation":"Open navigation")});nav.addEventListener("click",e=>{if(e.target.closest("a"))close()});document.addEventListener("click",e=>{if(!nav.contains(e.target)&&!menu.contains(e.target))close()});document.addEventListener("keydown",e=>{if(e.key==="Escape"){close();menu.focus()}})}
const carousel=document.querySelector("[data-carousel]");
if(carousel){const viewport=carousel.querySelector(".carousel-viewport"),track=carousel.querySelector(".carousel-track"),slides=[...carousel.querySelectorAll(".product-slide")],prev=carousel.querySelector(".prev"),next=carousel.querySelector(".next");let index=0,timer=null,startX=null;
const perView=()=>window.matchMedia("(max-width:780px)").matches?1:window.matchMedia("(max-width:1050px)").matches?2:3,maxIndex=()=>Math.max(0,slides.length-perView());
const render=()=>{index=Math.min(index,maxIndex());const first=slides[0],gap=parseFloat(getComputedStyle(track).gap)||0,amount=first?first.getBoundingClientRect().width+gap:0;track.style.transform="translateX(-"+index*amount+"px)";prev.disabled=index===0;next.disabled=index>=maxIndex()};
const stop=()=>{if(timer){clearInterval(timer);timer=null}},start=()=>{if(window.matchMedia("(prefers-reduced-motion:reduce)").matches)return;stop();timer=setInterval(()=>{index=index>=maxIndex()?0:index+1;render()},4500)};
prev.addEventListener("click",()=>{index=Math.max(0,index-1);render();start()});next.addEventListener("click",()=>{index=Math.min(maxIndex(),index+1);render();start()});viewport.addEventListener("mouseenter",stop);viewport.addEventListener("mouseleave",start);viewport.addEventListener("focusin",stop);viewport.addEventListener("focusout",start);viewport.addEventListener("touchstart",e=>startX=e.changedTouches[0].clientX,{passive:true});viewport.addEventListener("touchend",e=>{if(startX===null)return;const dx=e.changedTouches[0].clientX-startX;if(Math.abs(dx)>45){index=dx<0?Math.min(maxIndex(),index+1):Math.max(0,index-1);render()}startX=null},{passive:true});window.addEventListener("resize",render);render();start()}
const calc=document.querySelector("#roof-calculator");
if(calc){const v=id=>Number.parseFloat(document.querySelector("#"+id).value);calc.addEventListener("submit",e=>{e.preventDefault();const a=v("length"),w=v("width"),p=v("pitch"),sl=v("sheet-length"),cw=v("cover-width"),area=document.querySelector("#area-result"),sheets=document.querySelector("#sheet-result");if([a,w,p,sl,cw].some(n=>!Number.isFinite(n)||n<=0)){area.textContent="Enter all values";sheets.textContent="Enter all values";return}area.textContent=(a*w*p).toFixed(2)+" m²";sheets.textContent=Math.ceil((a*w*p)/(sl*cw))+" sheets"})}
})();